### ISSUE TITLE
Method to get addresses and names?

### ISSUE THREAD

**Issue by nitaybz** [davebeyer/homebridge-lutron-hwi#4]
Hey :)

Is there an easy way to get all the devices address and their names? or maybe just addresses so I can prepare the json file?
How did you guys made your json files? how did you know what addresses and where they belong to?

Thanks in advance 🙏

**Comment by davebeyer** [comment]
A straightforward method would be to generate an "Addressing" report from the HomeWorks Interactive application used to program the Lutron lighting processors in your home.    If the programming was done by a lighting contractor,  perhaps you can request the Addressing report from that contractor.

Otherwise, it seems you could theoretically monitor the [Homeworks Interactive commands](https://www.lutron.com/TechnicalDocumentLibrary/HWI%20RS232%20Protocol.pdf) that are copied out onto the Lutron processor's RS-232 port as you toggle switches around the house to see what addresses are used for each circuit.   You should see commands like:

```
DL, [01:01:02:02:04],  30
```

which is reporting that the circuit with address 01:01:02:02:04 is being dimmed to 30%.

**Comment by zelik888** [comment]
That's exactly how I did it, using the HWI application on my computer to downloa addressing and then doing some processing in excel to create the proper json entries. I've attached the excel sheet I created that did some simple sub/replacements (COL F H L due to some of the load wiring names needed to be cleaned up)
[example-lutron.xlsx](https://github.com/davebeyer/homebridge-lutron-hwi/files/8637985/example-lutron.xlsx)
.

**Comment by davebeyer** [comment]
It looks like you have commas between the parts of the address rather than periods.  E.g., try this instead:

```
  { "address" : "01.01.00.01.03", "name" : "1st Floor - Breakfast Nook - Bar"},
  ...
```

**Comment by zelik888** [comment]
Yeah that was a old file I found on another computer., i have it working with the periods!

**Comment by davebeyer** [comment]
Great!  Closing this issue.
